from datetime import datetime

# Save a simple text summary of the run to the reports/ folder.
# This is a basic backup report — the main report is the HTML file
# generated by pytest (reports/report.html).

with open("reports/report.txt", "w") as f:
    f.write("Airdrop QA Toolkit — Run Summary\n")
    f.write("---------------------------------\n")
    f.write(f"Generated: {datetime.now()}\n")
    f.write("Basic validation completed.\n")
    f.write("\nFor full results, open reports/report.html in your browser.\n")